#!/bin/bash
# 00-preflight.sh - Required tools, AWS/kubectl auth, cluster reachability,
# current fleet/state report, zbilling reachability. NO MUTATIONS.
#
# Usage: ./00-preflight.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source <(tr -d '\r' < "${SCRIPT_DIR}/config.env")
source "${SCRIPT_DIR}/_lib.sh"

step_banner "00" "Preflight (read-only)"

FAILURES=0
fail_check() {
    echo -e "${RED}✗${NC} $*"
    FAILURES=$((FAILURES + 1))
}

#------------------------------------------------------------------------------
# Required tools
#------------------------------------------------------------------------------

echo -e "${CYAN}Tools${NC}"
for cmd in aws terraform kubectl docker jq curl git openssl base64; do
    if command -v "${cmd}" >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} ${cmd}"
    else
        fail_check "${cmd} is not installed"
    fi
done
if command -v shellcheck >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} shellcheck (optional)"
fi
echo ""

#------------------------------------------------------------------------------
# AWS auth + region
#------------------------------------------------------------------------------

echo -e "${CYAN}AWS${NC}"
if AWS_CALLER_ARN=$(aws sts get-caller-identity --output text --query Arn 2>&1); then
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    export AWS_CALLER_ARN AWS_ACCOUNT_ID
    echo -e "${GREEN}✓${NC} Identity: ${AWS_CALLER_ARN}"
    echo "  Account: ${AWS_ACCOUNT_ID}  Region: ${AWS_REGION}"
else
    fail_check "AWS authentication failed: ${AWS_CALLER_ARN}"
fi

if aws ec2 describe-availability-zones --region "${AWS_REGION}" >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Region ${AWS_REGION} accessible"
else
    fail_check "region ${AWS_REGION} is not valid or not accessible"
fi
echo ""

#------------------------------------------------------------------------------
# Docker (needed for image builds in steps 05/08/10; warn only)
#------------------------------------------------------------------------------

echo -e "${CYAN}Docker${NC}"
if docker info >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Docker daemon is running"
else
    echo -e "${YELLOW}⚠${NC} Docker daemon not running — required before steps 05/08/10 (image builds)"
fi
echo ""

#------------------------------------------------------------------------------
# Cluster reachability
#------------------------------------------------------------------------------

echo -e "${CYAN}Cluster${NC}"
if kubectl auth can-i get deployments -n "${K8S_NAMESPACE_SYSTEM}" >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} kubectl authenticated to ${EKS_CLUSTER_NAME}"
    echo "  Nodes:"
    kubectl get nodes -o custom-columns='NAME:.metadata.name,STATUS:.status.conditions[-1].type,INSTANCE:.metadata.labels.node\.kubernetes\.io/instance-type,CONFIDENTIAL:.metadata.labels.swarm\.io/confidential-node' --no-headers \
        | sed 's/^/    /'
else
    fail_check "kubectl cannot reach ${EKS_CLUSTER_NAME} (try: aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER_NAME})"
fi
echo ""

#------------------------------------------------------------------------------
# Fleet / state report (agent counts by runtime class, schema version)
#------------------------------------------------------------------------------

print_fleet_report
echo ""

#------------------------------------------------------------------------------
# zbilling reachability (from the operator machine; the cluster path is
# verified implicitly by billing events once deployed)
#------------------------------------------------------------------------------

echo -e "${CYAN}zbilling${NC}"
Z_BILLING_URL="${Z_BILLING_URL:-https://z-billing.onrender.com}"
ZB_CODE=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 \
    "${Z_BILLING_URL}/health" 2>/dev/null || echo "000")
if [[ "${ZB_CODE}" == "200" ]]; then
    echo -e "${GREEN}✓${NC} ${Z_BILLING_URL}/health: 200 OK"
elif [[ "${ZB_CODE}" == "000" ]]; then
    fail_check "zbilling unreachable at ${Z_BILLING_URL}"
else
    echo -e "${YELLOW}⚠${NC} ${Z_BILLING_URL}/health returned HTTP ${ZB_CODE}"
fi
echo ""

#------------------------------------------------------------------------------
# Secrets folder
#------------------------------------------------------------------------------

echo -e "${CYAN}Secrets${NC}"
for secret in ANTHROPIC_API_KEY INTERNAL_TOKEN; do
    if [[ -n "$(load_secret "${secret}")" ]]; then
        echo -e "${GREEN}✓${NC} .secrets/${secret} present"
    else
        echo -e "${YELLOW}⚠${NC} .secrets/${secret} missing (INTERNAL_TOKEN is generated by step 03; ANTHROPIC_API_KEY must be created manually)"
    fi
done

#------------------------------------------------------------------------------
# Verdict
#------------------------------------------------------------------------------

if [[ ${FAILURES} -gt 0 ]]; then
    step_fail "${FAILURES} preflight check(s) failed — fix them before proceeding"
fi
step_ok "01 (./01-snp-node-group.sh)"
