#!/bin/bash
# 00-preflight.sh - Required tools, AWS/kubectl auth, cluster reachability,
# current fleet/state report, zbilling reachability. NO MUTATIONS.
#
# Usage: ./00-preflight.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source <(tr -d '\r' < "${SCRIPT_DIR}/config.env")
source "${SCRIPT_DIR}/_lib.sh"

step_banner "00" "Preflight (read-only)" "ops-admin"

FAILURES=0
fail_check() {
    log_err "$*"
    FAILURES=$((FAILURES + 1))
}

#------------------------------------------------------------------------------
# Required tools
#------------------------------------------------------------------------------

log_section "Tools"
for cmd in aws terraform kubectl helm docker jq curl git openssl base64 sha256sum; do
    if command -v "${cmd}" >/dev/null 2>&1; then
        log_ok "${cmd}"
    else
        fail_check "${cmd} is not installed"
    fi
done
if command -v shellcheck >/dev/null 2>&1; then
    log_ok "shellcheck (optional)"
fi

#------------------------------------------------------------------------------
# AWS auth + region
#------------------------------------------------------------------------------

log_section "AWS"
if AWS_CALLER_ARN=$(aws sts get-caller-identity --output text --query Arn 2>&1); then
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    export AWS_CALLER_ARN AWS_ACCOUNT_ID
    log_ok "Identity: ${AWS_CALLER_ARN}"
    log_kv "Account" "${AWS_ACCOUNT_ID}"
    log_kv "Region" "${AWS_REGION}"
else
    fail_check "AWS authentication failed: ${AWS_CALLER_ARN}"
fi

if aws ec2 describe-availability-zones --region "${AWS_REGION}" >/dev/null 2>&1; then
    log_ok "Region ${AWS_REGION} accessible"
else
    fail_check "region ${AWS_REGION} is not valid or not accessible"
fi

#------------------------------------------------------------------------------
# Docker (needed for image builds in steps 06/07/10/12; warn only)
#------------------------------------------------------------------------------

log_section "Docker"
DOCKER_INFO_TIMEOUT=15
if docker_daemon_ok "${DOCKER_INFO_TIMEOUT}"; then
    log_ok "Docker daemon is running"
else
    log_warn "Docker daemon not running (or not responding within ${DOCKER_INFO_TIMEOUT}s) — required before steps 06/07/10/12 (image builds)"
fi

#------------------------------------------------------------------------------
# Cluster reachability
#------------------------------------------------------------------------------

log_section "Cluster"
if kubectl auth can-i get deployments -n "${K8S_NAMESPACE_SYSTEM}" >/dev/null 2>&1; then
    log_ok "kubectl authenticated to ${EKS_CLUSTER_NAME}"
    log_detail "Nodes:"
    kubectl get nodes -o custom-columns='NAME:.metadata.name,STATUS:.status.conditions[-1].type,INSTANCE:.metadata.labels.node\.kubernetes\.io/instance-type,CONFIDENTIAL:.metadata.labels.swarm\.io/confidential-node' --no-headers \
        | indent
else
    fail_check "kubectl cannot reach ${EKS_CLUSTER_NAME} (try: aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER_NAME})"
fi

#------------------------------------------------------------------------------
# Fleet / state report (agent counts by runtime class, schema version)
#------------------------------------------------------------------------------

print_fleet_report

#------------------------------------------------------------------------------
# zbilling reachability (from the operator machine; the cluster path is
# verified implicitly by billing events once deployed)
#------------------------------------------------------------------------------

log_section "zbilling"
Z_BILLING_URL="${Z_BILLING_URL:-https://z-billing.onrender.com}"
ZB_CODE=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 \
    "${Z_BILLING_URL}/health" 2>/dev/null || echo "000")
if [[ "${ZB_CODE}" == "200" ]]; then
    log_ok "${Z_BILLING_URL}/health: 200 OK"
elif [[ "${ZB_CODE}" == "000" ]]; then
    fail_check "zbilling unreachable at ${Z_BILLING_URL}"
else
    log_warn "${Z_BILLING_URL}/health returned HTTP ${ZB_CODE}"
fi

#------------------------------------------------------------------------------
# Secrets folder
#------------------------------------------------------------------------------

log_section "Secrets"
for secret in INTERNAL_TOKEN; do
    if [[ -n "$(load_secret "${secret}")" ]]; then
        log_ok ".secrets/${secret} present"
    else
        log_warn ".secrets/${secret} missing (generated by step 04)"
    fi
done

#------------------------------------------------------------------------------
# Confidential runtime config (read-only consistency check)
#------------------------------------------------------------------------------

log_section "Confidential runtime"
validate_confidential_runtime_config || true

#------------------------------------------------------------------------------
# Verdict
#------------------------------------------------------------------------------

if [[ ${FAILURES} -gt 0 ]]; then
    step_fail "${FAILURES} preflight check(s) failed — fix them before proceeding"
fi
step_ok "01 (./01-iam.sh)"
