#!/bin/bash
# 02-deploy-network.sh - Deploy VPC and networking infrastructure
#
# Creates:
# - VPC (10.0.0.0/16)
# - Public subnet (10.0.1.0/24) for ALB
# - Private subnet (10.0.2.0/24) for platform services
# - Agent subnet (10.0.3.0/24) for microVM pods
# - Storage subnet (10.0.4.0/24) for EFS
# - Internet Gateway, NAT Gateway, route tables

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=============================================="
echo "  Aura Swarm - Deploy Network"
echo "=============================================="
echo ""

cd "${SCRIPT_DIR}/terraform"

#------------------------------------------------------------------------------
# Create tfvars file for this environment
#------------------------------------------------------------------------------

TFVARS_FILE="${SCRIPT_DIR}/terraform/terraform.tfvars"

cat > "${TFVARS_FILE}" <<EOF
# Auto-generated by deploy scripts
# Environment: ${ENVIRONMENT}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

aws_region          = "${AWS_REGION}"
project_name        = "${PROJECT_NAME}"
environment         = "${ENVIRONMENT}"

# Network configuration
vpc_cidr            = "${VPC_CIDR}"
public_subnet_cidr  = "${PUBLIC_SUBNET_CIDR}"
private_subnet_cidr = "${PRIVATE_SUBNET_CIDR}"
agent_subnet_cidr   = "${AGENT_SUBNET_CIDR}"
storage_subnet_cidr = "${STORAGE_SUBNET_CIDR}"

# EKS configuration
eks_version         = "${EKS_VERSION}"
node_instance_type  = "${NODE_INSTANCE_TYPE}"
node_desired_count  = ${NODE_DESIRED_COUNT}
node_min_count      = ${NODE_MIN_COUNT}
node_max_count      = ${NODE_MAX_COUNT}

# Feature flags - only deploy network for now
enable_network = true
enable_storage = false
enable_eks     = false
enable_ecr     = false
EOF

echo "Created terraform.tfvars with configuration"
echo ""

#------------------------------------------------------------------------------
# Plan and apply
#------------------------------------------------------------------------------

echo "Planning network infrastructure..."
echo ""

terraform plan -out=network.tfplan

echo ""
echo "=============================================="
echo -e "${YELLOW}Review the plan above before proceeding${NC}"
echo "=============================================="
echo ""
read -p "Apply this plan? (yes/no) [no]: " confirm
confirm=${confirm:-no}

if [[ "$confirm" != "yes" ]]; then
    echo "Aborted. Run this script again when ready."
    exit 0
fi

echo ""
echo "Applying network infrastructure..."
echo ""

terraform apply network.tfplan

echo ""
echo -e "${GREEN}=============================================="
echo "  Network deployed successfully!"
echo "==============================================${NC}"
echo ""

# Show outputs
echo "Network outputs:"
terraform output -json | jq -r '.vpc_id.value // empty' | xargs -I {} echo "  VPC ID: {}"
terraform output -json | jq -r '.nat_gateway_ip.value // empty' | xargs -I {} echo "  NAT Gateway IP: {}"

echo ""
echo "Next step: Run ./03-deploy-storage.sh"
