#!/bin/bash
# 06-build-harness.sh - Build, push, and pin the aura-harness image.
#
# The agent reasoning engine (aura-harness) lives in a SEPARATE repo
# (cypher-asi/aura-harness). This step clones it at HARNESS_REF (or builds a
# local checkout via HARNESS_REPO_PATH), builds the Docker image, pushes it to
# the harness ECR repo, resolves the immutable @sha256 digest, and persists it
# to .last-harness-image.env so the next step (07-deploy-r1) pins agent pods to
# it. Set AURA_HARNESS_IMAGE to a prebuilt @sha256 digest to skip the build.
#
# Usage:
#   ./06-build-harness.sh                                   # clone + build HARNESS_REF
#   HARNESS_REF=<git-ref> ./06-build-harness.sh             # build a specific ref
#   HARNESS_REPO_PATH=/path/to/aura-harness ./06-build-harness.sh   # build a local checkout
#   AURA_HARNESS_IMAGE=<registry>/...@sha256:... ./06-build-harness.sh  # skip build, pin explicit

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source <(tr -d '\r' < "${SCRIPT_DIR}/config.env")
source "${SCRIPT_DIR}/_lib.sh"

step_banner "06" "Build + pin the aura-harness image" "ops-admin"

HARNESS_REPO_URL="${HARNESS_REPO_URL:-https://github.com/cypher-asi/aura-harness}"
HARNESS_REF="${HARNESS_REF:-main}"
HARNESS_REPO_PATH="${HARNESS_REPO_PATH:-}"
HARNESS_REPO_NAME="${RESOURCE_PREFIX}-harness"

#------------------------------------------------------------------------------
# Short-circuit: an explicit immutable image was supplied — persist + done.
#------------------------------------------------------------------------------
if [[ -n "${AURA_HARNESS_IMAGE:-}" ]]; then
    [[ "${AURA_HARNESS_IMAGE}" =~ @sha256:[a-f0-9]{64}$ ]] \
        || step_fail "AURA_HARNESS_IMAGE must be pinned to an immutable digest (got: ${AURA_HARNESS_IMAGE})"
    {
        echo "# Auto-generated by 06-build-harness.sh (explicit AURA_HARNESS_IMAGE)"
        echo "AURA_HARNESS_IMAGE=${AURA_HARNESS_IMAGE}"
    } > "${HARNESS_STATE_FILE}"
    echo -e "${GREEN}✓${NC} Using provided pinned harness image: ${AURA_HARNESS_IMAGE}"
    echo -e "${GREEN}✓${NC} Persisted ${HARNESS_STATE_FILE}"
    step_ok "07 (./07-deploy-r1.sh)"
    exit 0
fi

require_cmds aws docker git jq
require_aws_auth
ecr_login

#------------------------------------------------------------------------------
# Resolve a build context: a local checkout (HARNESS_REPO_PATH) or a fresh,
# throwaway clone of HARNESS_REPO_URL at HARNESS_REF.
#------------------------------------------------------------------------------
CLEANUP_DIR=""
if [[ -n "${HARNESS_REPO_PATH}" ]]; then
    [[ -d "${HARNESS_REPO_PATH}" ]] || step_fail "HARNESS_REPO_PATH not found: ${HARNESS_REPO_PATH}"
    BUILD_CTX="${HARNESS_REPO_PATH}"
    echo "Building from local checkout: ${BUILD_CTX}"
else
    CLEANUP_DIR=$(mktemp -d)
    BUILD_CTX="${CLEANUP_DIR}/aura-harness"
    echo "Cloning ${HARNESS_REPO_URL} @ ${HARNESS_REF} (throwaway)..."
    if ! git clone --depth 1 --branch "${HARNESS_REF}" "${HARNESS_REPO_URL}" "${BUILD_CTX}" 2>/dev/null; then
        # HARNESS_REF may be a commit sha (not a branch/tag): full clone + checkout.
        git clone "${HARNESS_REPO_URL}" "${BUILD_CTX}" \
            || step_fail "could not clone ${HARNESS_REPO_URL}"
        git -C "${BUILD_CTX}" checkout "${HARNESS_REF}" \
            || step_fail "could not check out ref '${HARNESS_REF}' in ${HARNESS_REPO_URL}"
    fi
fi

[[ -f "${BUILD_CTX}/Dockerfile" ]] \
    || step_fail "no Dockerfile at ${BUILD_CTX} — is this the aura-harness repo root?"

HARNESS_GIT_SHA=$(git -C "${BUILD_CTX}" rev-parse HEAD 2>/dev/null || echo "")
[[ -n "${HARNESS_GIT_SHA}" ]] && echo "Harness git commit: ${HARNESS_GIT_SHA}"

#------------------------------------------------------------------------------
# Ensure the ECR repo, build, push.
#------------------------------------------------------------------------------
if ! aws ecr describe-repositories --repository-names "${HARNESS_REPO_NAME}" >/dev/null 2>&1; then
    echo "Creating ECR repository: ${HARNESS_REPO_NAME}"
    aws ecr create-repository --repository-name "${HARNESS_REPO_NAME}" \
        --image-scanning-configuration scanOnPush=true >/dev/null
fi

REGISTRY=$(ecr_registry)
HARNESS_IMAGE="${REGISTRY}/${HARNESS_REPO_NAME}:${IMAGE_TAG}"

echo "Building ${HARNESS_REPO_NAME}:${IMAGE_TAG}..."
if ! docker build \
    --progress=plain \
    --build-arg GIT_SHA="${HARNESS_GIT_SHA}" \
    -t "${HARNESS_IMAGE}" \
    -f "${BUILD_CTX}/Dockerfile" "${BUILD_CTX}"; then
    [[ -n "${CLEANUP_DIR}" ]] && rm -rf "${CLEANUP_DIR}"
    step_fail "aura-harness docker build failed"
fi

if ! docker push "${HARNESS_IMAGE}"; then
    [[ -n "${CLEANUP_DIR}" ]] && rm -rf "${CLEANUP_DIR}"
    step_fail "aura-harness docker push failed"
fi
echo -e "${GREEN}✓${NC} Pushed ${HARNESS_IMAGE}"

#------------------------------------------------------------------------------
# Resolve the immutable digest + persist deploy state for step 07.
#------------------------------------------------------------------------------
DIGEST=$(aws ecr describe-images \
    --repository-name "${HARNESS_REPO_NAME}" \
    --image-ids imageTag="${IMAGE_TAG}" \
    --query 'imageDetails[0].imageDigest' \
    --output text 2>/dev/null || echo "")
[[ -n "${CLEANUP_DIR}" ]] && rm -rf "${CLEANUP_DIR}"

[[ -n "${DIGEST}" && "${DIGEST}" != "None" ]] \
    || step_fail "could not resolve the harness image digest after push"

PINNED_HARNESS_IMAGE="${REGISTRY}/${HARNESS_REPO_NAME}@${DIGEST}"
{
    echo "# Auto-generated by 06-build-harness.sh"
    echo "AURA_HARNESS_IMAGE=${PINNED_HARNESS_IMAGE}"
    echo "AURA_HARNESS_TAGGED_IMAGE=${HARNESS_IMAGE}"
    echo "AURA_HARNESS_DIGEST=${DIGEST}"
    echo "AURA_HARNESS_GIT_SHA=${HARNESS_GIT_SHA}"
} > "${HARNESS_STATE_FILE}"

echo -e "${GREEN}✓${NC} Pinned harness image: ${PINNED_HARNESS_IMAGE}"
echo -e "${GREEN}✓${NC} Persisted ${HARNESS_STATE_FILE}"

step_ok "07 (./07-deploy-r1.sh)"
