#!/bin/bash
# 08-efs-backup.sh - On-demand AWS Backup recovery point for the swarm EFS
# filesystem. This is the R2 ROLLBACK POINT: take it immediately before
# running ./09-deploy-r2-migrate.sh.
#
# The terraform storage module already enables AWS Backup (automatic daily
# policy); this script adds an explicit on-demand recovery point and waits
# for it to complete, persisting the ARN in deploy/.last-efs-backup.env.
#
# Usage: ./08-efs-backup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source <(tr -d '\r' < "${SCRIPT_DIR}/config.env")
source "${SCRIPT_DIR}/_lib.sh"

step_banner "08" "EFS backup (R2 rollback point)"

require_cmds aws terraform jq
require_aws_auth

#------------------------------------------------------------------------------
# Resolve the filesystem + backup role
#------------------------------------------------------------------------------

EFS_ARN=$(tf_output efs_filesystem_arn)
EFS_ID=$(tf_output efs_filesystem_id)
[[ -n "${EFS_ARN}" ]] || step_fail "could not read the EFS filesystem ARN from terraform output"
echo "Filesystem: ${EFS_ID}"

BACKUP_VAULT="${BACKUP_VAULT_NAME:-Default}"
aws backup describe-backup-vault --backup-vault-name "${BACKUP_VAULT}" >/dev/null 2>&1 \
    || step_fail "backup vault '${BACKUP_VAULT}' does not exist (set BACKUP_VAULT_NAME or create it)"

BACKUP_ROLE_ARN="${BACKUP_ROLE_ARN:-arn:aws:iam::${AWS_ACCOUNT_ID}:role/service-role/AWSBackupDefaultServiceRole}"
if ! aws iam get-role --role-name "$(basename "${BACKUP_ROLE_ARN}")" >/dev/null 2>&1; then
    step_fail "backup IAM role not found: ${BACKUP_ROLE_ARN} (set BACKUP_ROLE_ARN, or create the AWS Backup default service role in the console)"
fi

#------------------------------------------------------------------------------
# Start the on-demand backup job
#------------------------------------------------------------------------------

echo "Starting on-demand backup job into vault '${BACKUP_VAULT}'..."
JOB_ID=$(aws backup start-backup-job \
    --backup-vault-name "${BACKUP_VAULT}" \
    --resource-arn "${EFS_ARN}" \
    --iam-role-arn "${BACKUP_ROLE_ARN}" \
    --recovery-point-tags "Purpose=pre-r2-migration,Project=${PROJECT_NAME},Environment=${ENVIRONMENT}" \
    --query 'BackupJobId' --output text)
echo "  Backup job: ${JOB_ID}"

#------------------------------------------------------------------------------
# Wait for completion
#------------------------------------------------------------------------------

TIMEOUT="${EFS_BACKUP_TIMEOUT_SECS:-7200}"
POLL=30
ELAPSED=0
STATE=""
RECOVERY_POINT_ARN=""

while [[ ${ELAPSED} -le ${TIMEOUT} ]]; do
    JOB_JSON=$(aws backup describe-backup-job --backup-job-id "${JOB_ID}")
    STATE=$(echo "${JOB_JSON}" | jq -r '.State')
    RECOVERY_POINT_ARN=$(echo "${JOB_JSON}" | jq -r '.RecoveryPointArn // empty')
    PERCENT=$(echo "${JOB_JSON}" | jq -r '.PercentDone // "0"')
    case "${STATE}" in
        COMPLETED) break ;;
        ABORTED|FAILED|EXPIRED)
            echo "${JOB_JSON}" | jq '{State, StatusMessage}'
            step_fail "backup job ${JOB_ID} ended in state ${STATE}"
            ;;
    esac
    echo "  [${ELAPSED}s] state=${STATE} progress=${PERCENT}%"
    sleep "${POLL}"
    ELAPSED=$((ELAPSED + POLL))
done

[[ "${STATE}" == "COMPLETED" ]] || step_fail "backup job did not complete within ${TIMEOUT}s (job ${JOB_ID})"
[[ -n "${RECOVERY_POINT_ARN}" ]] || step_fail "backup completed but no recovery point ARN was reported"

#------------------------------------------------------------------------------
# Verify the recovery point and persist its ARN
#------------------------------------------------------------------------------

RP_STATUS=$(aws backup describe-recovery-point \
    --backup-vault-name "${BACKUP_VAULT}" \
    --recovery-point-arn "${RECOVERY_POINT_ARN}" \
    --query 'Status' --output text)
[[ "${RP_STATUS}" == "COMPLETED" ]] \
    || step_fail "recovery point status is ${RP_STATUS}, expected COMPLETED"

{
    echo "# Auto-generated by 08-efs-backup.sh"
    echo "EFS_BACKUP_RECOVERY_POINT_ARN=${RECOVERY_POINT_ARN}"
    echo "EFS_BACKUP_VAULT=${BACKUP_VAULT}"
    echo "EFS_BACKUP_FILESYSTEM_ID=${EFS_ID}"
    echo "EFS_BACKUP_TAKEN_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
} > "${EFS_BACKUP_STATE_FILE}"

echo -e "${GREEN}✓${NC} Recovery point COMPLETED: ${RECOVERY_POINT_ARN}"
echo -e "${GREEN}✓${NC} Rollback point recorded in ${EFS_BACKUP_STATE_FILE}"
echo ""
echo "Rollback procedure (if R2 goes wrong): restore this recovery point,"
echo "redeploy the R1 images (./06-deploy-r1.sh), and unset"
echo "MIGRATION_RECREATE_LEGACY_PODS in the aura-swarm-config ConfigMap."

step_ok "09 (./09-deploy-r2-migrate.sh)"
